# Utilise l'image passbolt/passbolt:latest comme base
FROM passbolt/passbolt:latest

# Mettre à jour la liste des paquets et installer wget
RUN apt-get update && apt-get install -y wget

# Expose le port 443
EXPOSE 443
